version: "3.8"

services:
  back:
    build: ./back
    container_name: back_p7
    environment:
     DB_USR: /run/secrets/db_usr
     DB_PASS: /run/secrets/db_pass
     DB_NAME: /run/secrets/db_name
     DB_HOST: database
     DB_PORT: 3306
    secrets:
     - db_usr
     - db_pass
     - db_name 
    volumes:
     - ./back:/app
    ports:
     - 3000:3000
    networks:
     - front-net
     - back-net
    restart: unless-stopped

  front:
   build: ./front_app
   container_name: front_p7
   volumes:
     - ./front_app:/app
   ports:
    - 8080:80
   networks:
    - front-net
   restart: unless-stopped

  database:
    image: mysql:latest
    container_name: db_p7
    environment:
     MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root
     MYSQL_PASSWORD_FILE: /run/secrets/db_pass
     MYSQL_USER_FILE: /run/secrets/db_usr
     MYSQL_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - db_root
      - db_pass
      - db_usr 
      - db_name 
    networks:
     - back-net

networks:
  back-net:
  front-net:

secrets:
  db_root:
   file: ./secrets/db_root
  db_pass:
   file: ./secrets/db_pass
  db_usr:
   file: ./secrets/db_usr
  
  db_name:
   file: ./secrets/db_name
