version: "3.8"

services:
  back:
    build: ./back
    container_name: back_p7
    image: uchopard/back_groupomania
    environment:
     DB_USR_FILE: /run/secrets/db_usr
     DB_PASS_FILE: /run/secrets/db_pass
     DB_NAME_FILE: /run/secrets/db_name
     DB_HOST: database
     MODERATOR_PASS_FILE: /run/secrets/moderator_pass
    secrets:
     - db_usr
     - db_pass
     - db_name 
     - moderator_pass
    ports:
     - 3000:3000
    networks:
     - frontend
     - backend
    restart: unless-stopped
    depends_on:
      - database

  front:
   build: ./front
   container_name: front_p7
   image: uchopard/front_groupomania
   ports:
    - 8080:80
   networks:
    - frontend
   restart: unless-stopped
   depends_on:
    - back

  database:
    image: mysql:latest
    container_name: db_p7
    environment:
     MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root
     MYSQL_PASSWORD_FILE: /run/secrets/db_pass
     MYSQL_USER_FILE: /run/secrets/db_usr
     MYSQL_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - db_root
      - db_pass
      - db_usr 
      - db_name 
    networks:
     - backend
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 20s

networks:
  backend:
  frontend:

secrets:
  db_root:
   file: ./secrets/db_root
  db_pass:
   file: ./secrets/db_pass
  db_usr:
   file: ./secrets/db_usr
  
  db_name:
   file: ./secrets/db_name
  moderator_pass:
   file: ./secrets/moderator_pass

volumes:
  data:
